columns_map:
  timestamp: "Marca temporal"
  origen: "¿Cúal es su lugar de residencia?"
  ciudad_es: "En el caso de que haya marcado anteriormente que su lugar de residencia NO es Alcoi. ¿Podría especificar de dónde es? (país, provincia, municipio...)"
  # pais_intl: "En el caso de Internacional, ¿qué país?"
  n_adultos: "¿Con cuántas personas viaja?"
  tourist_info: "¿Con cuántas personas de las que viaja han entrado a las Tourist-Info?"
  wifi: "Con el fin de mejorar nuestros servicios de información turística. ¿Me podría indicar si tiene el Wifi de su teléfono móvil abierto para conectarse a redes Wifi disponibles?"
 
schema:
  required: [timestamp, origen, n_adultos]
 
types:
  timestamp: datetime
  origen: category
  ciudad_es: string
  n_adultos: int
  tourist_info: int
  wifi: category
 
domains:
  origen:
    allowed: ["Alcoi", "España", "Internacional", "Comunidad Valenciana"]
  wifi:
    allowed: ["Sí", "No", "No entiendo la pregunta"]
 
ranges:
  n_adultos: {min: 0, max: 10}
  tourist_info: {min: 0, max: 10}
 
uniques:
  - timestamp
 
conditionals:
  - if: {origen: "España"}
    then: {require_not_null: ["ciudad_es"]}
  - if: {origen: "Internacional"}
    then: {require_not_null: ["ciudad_es"]}
  - rule: "n_adultos + tourist_info >= 1"
 
severity:
  missing_column: error
  type_mismatch: error
  domain_violation: warning
  range_violation: warning
  uniqueness_violation: error
  conditional_violation: error